# cargo-deny configuration for MSBuild-RS
# See https://github.com/EmbarkStudios/cargo-deny for documentation

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
]

[licenses]
# Allow these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]

# Deny these licenses
deny = ["GPL-2.0", "GPL-3.0", "AGPL-1.0", "AGPL-3.0"]

# Allow these specific crates with non-standard licenses
[[licenses.exceptions]]
allow = ["OpenSSL"]
name = "ring"

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Skip certain crates when checking for multiple versions
skip = [
    # Windows-specific crates often have multiple versions
    { name = "windows-sys" },
    { name = "windows_x86_64_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_aarch64_msvc" },
]

# Deny specific crates
deny = [
    # Crates with known security issues
    { name = "openssl", version = "<0.10.55" },
    # Crates that are deprecated or have better alternatives
    { name = "failure" },
    { name = "error-chain" },
]

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# The lint level for security vulnerabilities
vulnerability = "deny"

# The lint level for unmaintained crates
unmaintained = "all"

# The lint level for crates that have been yanked from their source registry
yanked = "warn"

# The lint level for crates with security notices
notice = "warn"

# A list of advisory IDs to ignore
ignore = [
    # Add any advisory IDs you want to ignore here
    # Example: "RUSTSEC-2020-0001",
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"

# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of allowed Git repositories
allow-git = []
